# Generated by Django 3.0.3 on 2020-02-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgdb', '0012_auto_20190819_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='average_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='average_weight',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bayes_average_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_play_time',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_players',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='median',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_age',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_play_time',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_players',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='num_comments',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='num_ratings',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='num_weights',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='owned',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='playing_time',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='standard_deviation',
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='trading',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='wanting',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='wishing',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='year_published',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
